[project]
name = "test-langfuse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.76.0",
    "langfuse>=3.12.1",
    "openai>=2.16.0",
    "opentelemetry-instrumentation-anthropic>=0.51.1",
]
